name: Lavastone Benchmark CI Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update 
        sudo apt install build-essential cmake libleveldb-dev libzstd-dev libboost-dev
    - name: Build Lavastone
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --parallel
        ./test_lavastone 10000

