name: Lavastone Library CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install build-essential cmake libleveldb-dev \
          librocksdb-dev libzstd-dev libboost-dev \
          libboost-serialization-dev libsnappy-dev sqlite3 \
          git
        git clone --recursive https://github.com/google/leveldb.git
        cd leveldb
        git checkout 99b3c03b3284f5886f9ef9a4ef703d57373e61be
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --parallel
        sudo make install
    - name: Install dependencies on Mac
      if: runner.os == 'macOS'
      run: |
        brew install cmake leveldb zstd boost
    - name: Build Lavastone
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --parallel
        ./test_lavastone 10000
